name: Testing setting env vars between steps

on: [push, workflow_dispatch]

jobs:

  testvar:

    runs-on: ubuntu-latest

    env:

      DATA_CHANGED: 0

    steps:

      - name: Set var
        run: |
          echo $DATA_CHANGED
          echo "DATA_CHANGED=1" >> $GITHUB_ENV
          echo $DATA_CHANGED

      - name: Run if var
        if: ${{ env.DATA_CHANGED == 1}}
        run: echo "The data has changed"